name: Generate page
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-tutorial-sync
      - trigger-document-sync
  pull_request:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependents
        run: |
          pip install mkdocs-material=="9.*" mkdocs-static-i18n=="0.53"
          pip install "mkdocs-material[imaging]"

      - name: Build page
        if: github.event_name == 'pull_request'
        run: |
          mkdocs build -v

      - name: Deploy page
        if: |
          github.event_name == 'repository_dispatch' ||
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch'
        run: |
          mkdocs gh-deploy -m "{sha}" --force --ignore-version --no-history
